#docker-compose.yml
#Engineer:  T. Looby
#Date: 20220124
#Description: Docker recipe for development.  Generates environment.
#             requires user to have the volumes below locally on host
#             if not, comment out the line for the dir you don't have
#             if so, change paths to match your machine
version: "3.3"

services:
  HEAT:
    user: ${UID}:${GID}
    build:
      context: .
      args:
        HOST_USER: ${USER}
        HOST_UID: ${UID}
        HOST_GID: ${GID}
    image: "plasmapotential/heat:heatuser"
    ports:
      - "8050:8050"
    volumes:
      #change volumes below to match your development (host) machine
      #format is: /host/path:/container/path
      #user should not edit container paths
      #
      # HEAT data directory on this machine (if exists)
      - ${HOME}/HEAT:/home/heatuser/HEAT
      # HEAT source code from github
#      - /home/tom/source/HEAT/github/source:/home/heatuser/source/HEAT
#      # ORNL EFIT class from github (if you have access, else in container)
#      - /home/tom/source/EFIT:/root/EFIT
#      # MAFOT bins and libs
#      - /home/tom/source/HEAT/MAFOT/bin:/root/opt/mafot/bin
#      - /home/tom/source/HEAT/MAFOT/lib:/root/opt/mafot/lib
#      # openFOAM bins and libs
#      - /opt/openfoam/OpenFOAM-v2106/bin:/root/opt/openfoam/bin
#      - /opt/openfoam/OpenFOAM-v2106/lib:/root/opt/openfoam/lib
#      #swak4foam bins / libs
#      - /home/tom/OpenFOAM/tom-v2106/platforms/linux64GccDPInt32Opt/bin:/root/opt/swak4foam/bin
#      - /home/tom/OpenFOAM/tom-v2106/platforms/linux64GccDPInt32Opt/lib:/root/opt/swak4foam/lib
#      # Batch mode directory
#      - /home/tom/HEATruns/SPARC/fishScale_T5B:/home/heatuser/terminal
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    #if you want to set env vars, do it here:
    environment:
    #- dockerUID=$dockerUID
    #- dockerGID=$dockerGID
    #- UID=$dockerUID
    #- GID=$dockerGID
    - HOST_USER=heatuser
    - HOST_UID=${HOST_UID:-1000}
    - HOST_GID=${HOST_GID:-1000}



#NOTES:
#to run HEAT in batch mode, first bind mount the /root/terminal directory to your
#local directory with the batchFile, then run:
# python3 launchHEAT.py --m t --f /root/terminal/batchFile.dat
#
#to run an interactive shell use this command:
# docker-compose run HEAT /bin/bash
#
# to change image tag name:
# docker tag plasmapotential/heat:latest plasmapotential/heat:<tag>
